/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jmfvideoimage;

import controlador.conexion;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author GANDHY
 */
public class ProveedoresEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form ProveedoresEmpleados
     */
    public ProveedoresEmpleados() {
        initComponents();
          ///////////////////////////lenar combobox
        codigoActividadEconomica();
        //nos manda al metodo que nos desabilita todos los campos con el fin de que se activen los campos segun el radiobutton que seleccione el usuario 
        //desabilitaHastaSeleccionar();

        //nos manda al metodo que se encarga de ir a traer los tipos de documentos
        seleccioneTipoDocumento();

        //nos manda al metodo que se encarga de ir a traer los diferentes paises
        seleccionePais();

        //nos manda al metodo que se encarga de ir a traer los diferentes departamentos
        seleccioneDepartamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jCnaturaleza = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jTrazonSocial = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jTnroIdentif = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jTdigitoVerifi = new javax.swing.JTextField();
        jTdireccion = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTtelefono = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jCactividadEco = new javax.swing.JComboBox();
        jLabel59 = new javax.swing.JLabel();
        jCcodigoPais = new javax.swing.JComboBox();
        jLabel60 = new javax.swing.JLabel();
        jCcodigoDepart = new javax.swing.JComboBox();
        jLabel61 = new javax.swing.JLabel();
        jCcodigoMunic = new javax.swing.JComboBox();
        jLdescripcion = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jTid = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLnombres1 = new javax.swing.JLabel();
        jTnombres = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTotrosNombre = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTapellidos = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTsegundoApellido = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jCtipoDocumento = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jtficha1 = new javax.swing.JTextField();
        jBabrir1 = new javax.swing.JButton();
        jbtnCargaDocumento = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jtficha2 = new javax.swing.JTextField();
        jBabrir4 = new javax.swing.JButton();
        jbtnCargaDocumento3 = new javax.swing.JButton();
        jLabel62 = new javax.swing.JLabel();
        jTnroIdentifCliente = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTAinfoCedulaOriginal = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jBguardar = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jBmodificar = new javax.swing.JToggleButton();
        jBbuscar = new javax.swing.JToggleButton();
        jLusuario1 = new javax.swing.JLabel();
        jLusuario = new javax.swing.JLabel();
        jLrol1 = new javax.swing.JLabel();
        jLrol = new javax.swing.JLabel();
        jLfecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 0, 204))); // NOI18N

        jLabel13.setText("Naturaleza:");

        jCnaturaleza.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Persona juridica", "Persona natural", "Empleado" }));

        jLabel14.setText("Nombre Empleado:");

        jLabel55.setText("Nro identif: *");

        jTnroIdentif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTnroIdentifFocusLost(evt);
            }
        });
        jTnroIdentif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnroIdentifActionPerformed(evt);
            }
        });
        jTnroIdentif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTnroIdentifKeyPressed(evt);
            }
        });

        jLabel56.setText("Dig verifica:");

        jTdigitoVerifi.setEditable(false);

        jLabel57.setText("Direccion:*");

        jLabel15.setText("Tel. Fijo (codigo area + fijo):*");

        jTtelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtelefonoKeyPressed(evt);
            }
        });

        jLabel58.setText("Act. econo:");

        jCactividadEco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCactividadEcoActionPerformed(evt);
            }
        });

        jLabel59.setText("Cod. pais:");

        jLabel60.setText("Cod. departamento:");

        jCcodigoDepart.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCcodigoDepartItemStateChanged(evt);
            }
        });

        jLabel61.setText("Cod. municip:*");

        jLabel64.setText("Email");

        jTid.setEditable(false);
        jTid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTidActionPerformed(evt);
            }
        });

        jLabel8.setText("Id:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57)
                            .addComponent(jLabel58))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel61)
                                .addGap(24, 24, 24)
                                .addComponent(jCcodigoMunic, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jCactividadEco, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jCcodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel59))
                                .addGap(32, 32, 32)
                                .addComponent(jLabel60)
                                .addGap(18, 18, 18)
                                .addComponent(jCcodigoDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel64)
                                .addGap(24, 24, 24)
                                .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)
                        .addComponent(jCnaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addGap(14, 14, 14)
                        .addComponent(jTrazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTnroIdentif, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel56)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdigitoVerifi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTrazonSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jCnaturaleza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel55))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel56)
                        .addComponent(jTnroIdentif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTdigitoVerifi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTid, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel57)
                        .addComponent(jTdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15)
                        .addComponent(jTtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel61))
                    .addComponent(jCcodigoMunic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel58)
                    .addComponent(jCactividadEco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(jCcodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(jCcodigoDepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel64)
                    .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 17, Short.MAX_VALUE)
                .addComponent(jLdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Persona Autorizada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 204))); // NOI18N

        jLnombres1.setText("Primer nombre:*");

        jTnombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTnombresFocusLost(evt);
            }
        });

        jLabel11.setText("Otros nombre:");

        jTotrosNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTotrosNombreFocusLost(evt);
            }
        });

        jLabel53.setText("Primer Apellido: *");

        jTapellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTapellidosFocusLost(evt);
            }
        });

        jLabel12.setText("Segundo apellido:");

        jTsegundoApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTsegundoApellidoFocusLost(evt);
            }
        });

        jLabel54.setText("Tipo de docum:");

        jLabel20.setText("Carta de Autorización: *");

        jtficha1.setEditable(false);

        jBabrir1.setText("Abrir");
        jBabrir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabrir1ActionPerformed(evt);
            }
        });

        jbtnCargaDocumento.setText("Cargar Archivo");
        jbtnCargaDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargaDocumentoActionPerformed(evt);
            }
        });

        jLabel21.setText("Fotocopia Cedula: *");

        jtficha2.setEditable(false);

        jBabrir4.setText("Abrir");
        jBabrir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBabrir4ActionPerformed(evt);
            }
        });

        jbtnCargaDocumento3.setText("Cargar Archivo");
        jbtnCargaDocumento3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCargaDocumento3ActionPerformed(evt);
            }
        });

        jLabel62.setText("Nro identif: *");

        jTnroIdentifCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTnroIdentifClienteFocusLost(evt);
            }
        });
        jTnroIdentifCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnroIdentifClienteActionPerformed(evt);
            }
        });
        jTnroIdentifCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTnroIdentifClienteKeyPressed(evt);
            }
        });

        jTAinfoCedulaOriginal.setColumns(20);
        jTAinfoCedulaOriginal.setRows(5);
        jTAinfoCedulaOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTAinfoCedulaOriginalFocusLost(evt);
            }
        });
        jTAinfoCedulaOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTAinfoCedulaOriginalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTAinfoCedulaOriginalKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(jTAinfoCedulaOriginal);

        jLabel23.setForeground(new java.awt.Color(255, 0, 0));
        jLabel23.setText("Info Cedula: *");

        jBguardar.setText("GUARDAR");
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });

        jToggleButton3.setText("NUEVO");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jBmodificar.setText("MODIFICAR");
        jBmodificar.setEnabled(false);
        jBmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmodificarActionPerformed(evt);
            }
        });

        jBbuscar.setText("BUSCAR");
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtficha2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBabrir4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnCargaDocumento3))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 543, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtficha1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBabrir1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnCargaDocumento)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jBbuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBmodificar)
                            .addComponent(jToggleButton3))
                        .addGap(140, 140, 140))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLnombres1)
                            .addComponent(jLabel54))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jCtipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel62)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jTotrosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel53)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTsegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTnroIdentifCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBguardar)
                            .addComponent(jBmodificar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleButton3)
                            .addComponent(jBbuscar)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLnombres1)
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(jTnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTotrosNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel53)
                                .addComponent(jTapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(jTsegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel54)
                                .addComponent(jCtipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel62)
                                .addComponent(jTnroIdentifCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jtficha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCargaDocumento)
                            .addComponent(jBabrir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jtficha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnCargaDocumento3)
                            .addComponent(jBabrir4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel23)))))
                .addGap(21, 21, 21))
        );

        jLusuario1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/userlo.png"))); // NOI18N

        jLrol1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/rol.png"))); // NOI18N

        jLfecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cal.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLusuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLrol1)
                .addGap(18, 18, 18)
                .addComponent(jLrol, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLusuario1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLrol1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLrol, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLfecha)))
                        .addComponent(jLusuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTnroIdentifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnroIdentifFocusLost

        String nit = jTnroIdentif.getText();
        long nitl = Long.parseLong(nit);

        int[] nums = {
            3, 7, 13, 17, 19, 23, 29, 37, 41, 43, 47, 53, 59, 67, 71
        };

        int sum = 0;

        String str = String.valueOf(nitl);
        for (int i = str.length() - 1, j = 0; i >= 0; i--, j++) {
            sum += Character.digit(str.charAt(i), 10) * nums[j];
        }

        byte dv = (byte) ((sum % 11) > 1 ? (11 - (sum % 11)) : (sum % 11));
        JOptionPane.showMessageDialog(null, "  digito verificacion  " + dv);

        jTdigitoVerifi.setText("" + dv);
    }//GEN-LAST:event_jTnroIdentifFocusLost

    private void jTnroIdentifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnroIdentifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnroIdentifActionPerformed

    private void jTnroIdentifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnroIdentifKeyPressed
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este es un Campo Numerico");
        }
    }//GEN-LAST:event_jTnroIdentifKeyPressed

    private void jTtelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtelefonoKeyPressed
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este es un Campo Numerico");
        }
    }//GEN-LAST:event_jTtelefonoKeyPressed

    private void jCactividadEcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCactividadEcoActionPerformed

        try {
            //llamamos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            String coActividad = (String) jCactividadEco.getSelectedItem();

            ResultSet resultado = estado.executeQuery("SELECT * FROM acteconomicas  WHERE  codigo = '" + coActividad + "'  ");

            String descripcion = null;

            while (resultado.next()) {

                descripcion = resultado.getString("descripcion");

            }

            jLdescripcion.setText(descripcion);

        } catch (SQLException ex) {

            System.out.println(ex);

        }
    }//GEN-LAST:event_jCactividadEcoActionPerformed

    private void jCcodigoDepartItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCcodigoDepartItemStateChanged

        jCcodigoMunic.removeAllItems();//remueve los item para que se actualice con cada eleccion
        selectcodmunicipio();
    }//GEN-LAST:event_jCcodigoDepartItemStateChanged

    private void jTidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTidActionPerformed

    private void jTnombresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnombresFocusLost

        jTnombres.setText(jTnombres.getText().toUpperCase());
    }//GEN-LAST:event_jTnombresFocusLost

    private void jTotrosNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTotrosNombreFocusLost

        jTotrosNombre.setText(jTotrosNombre.getText().toUpperCase());
    }//GEN-LAST:event_jTotrosNombreFocusLost

    private void jTapellidosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTapellidosFocusLost

        jTapellidos.setText(jTapellidos.getText().toUpperCase());
    }//GEN-LAST:event_jTapellidosFocusLost

    private void jTsegundoApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTsegundoApellidoFocusLost

        jTsegundoApellido.setText(jTsegundoApellido.getText().toUpperCase());
    }//GEN-LAST:event_jTsegundoApellidoFocusLost

    private void jBabrir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabrir1ActionPerformed
        // abre el documento de la ficha tecnica 1

        String ruta = jtficha1.getText();
        try {
            File path = new File(ruta);
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showInternalMessageDialog(null, "El Archivo no puede ser Abierto");
        }
    }//GEN-LAST:event_jBabrir1ActionPerformed

    private void jbtnCargaDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargaDocumentoActionPerformed
        // solo carga documentos:

        File archivo;
        JFileChooser flcAbrirArchivo = new JFileChooser();
        flcAbrirArchivo.setFileFilter(new FileNameExtensionFilter("Archivo ficha Tecnica", "doc", "docx", "pdf", "xlm", "xlms", "jpg", "png", "bmp"));
        int respuesta = flcAbrirArchivo.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            archivo = flcAbrirArchivo.getSelectedFile();
            jtficha1.setText(archivo.getAbsolutePath());

        }
    }//GEN-LAST:event_jbtnCargaDocumentoActionPerformed

    private void jBabrir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBabrir4ActionPerformed
        String ruta = jtficha2.getText();
        try {
            File path = new File(ruta);
            Desktop.getDesktop().open(path);
        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showInternalMessageDialog(null, "El Archivo no puede ser Abierto");
        }
    }//GEN-LAST:event_jBabrir4ActionPerformed

    private void jbtnCargaDocumento3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCargaDocumento3ActionPerformed
        // solo carga documentos:

        File archivo;
        JFileChooser flcAbrirArchivo = new JFileChooser();
        flcAbrirArchivo.setFileFilter(new FileNameExtensionFilter("Archivo ficha Tecnica", "doc", "docx", "pdf", "xlm", "xlms", "jpg", "png", "bmp"));
        int respuesta = flcAbrirArchivo.showOpenDialog(this);
        if (respuesta == JFileChooser.APPROVE_OPTION) {
            archivo = flcAbrirArchivo.getSelectedFile();
            jtficha2.setText(archivo.getAbsolutePath());

        }
    }//GEN-LAST:event_jbtnCargaDocumento3ActionPerformed

    private void jTnroIdentifClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTnroIdentifClienteFocusLost

    }//GEN-LAST:event_jTnroIdentifClienteFocusLost

    private void jTnroIdentifClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnroIdentifClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnroIdentifClienteActionPerformed

    private void jTnroIdentifClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTnroIdentifClienteKeyPressed
        if (evt.getKeyChar() < '0' || evt.getKeyChar() > '9') {
            evt.consume();
            JOptionPane.showMessageDialog(this, "Este es un Campo Numerico");
        }
    }//GEN-LAST:event_jTnroIdentifClienteKeyPressed

    private void jTAinfoCedulaOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTAinfoCedulaOriginalFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAinfoCedulaOriginalFocusLost

    private void jTAinfoCedulaOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAinfoCedulaOriginalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAinfoCedulaOriginalKeyPressed

    private void jTAinfoCedulaOriginalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTAinfoCedulaOriginalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTAinfoCedulaOriginalKeyTyped

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // VERIFICA SI EL EMPLEADO EXISTE Y LUEGO LO GUARDA
        verificacionEmpleado();
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        limpiar();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jBmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmodificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBmodificarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed

        buscanit();
    }//GEN-LAST:event_jBbuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProveedoresEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProveedoresEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProveedoresEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProveedoresEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProveedoresEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBabrir1;
    private javax.swing.JButton jBabrir4;
    private javax.swing.JToggleButton jBbuscar;
    private javax.swing.JToggleButton jBguardar;
    private javax.swing.JToggleButton jBmodificar;
    private javax.swing.JComboBox jCactividadEco;
    private javax.swing.JComboBox jCcodigoDepart;
    private javax.swing.JComboBox jCcodigoMunic;
    private javax.swing.JComboBox jCcodigoPais;
    private javax.swing.JComboBox jCnaturaleza;
    private javax.swing.JComboBox jCtipoDocumento;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLdescripcion;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JLabel jLnombres1;
    private javax.swing.JLabel jLrol;
    private javax.swing.JLabel jLrol1;
    private javax.swing.JLabel jLusuario;
    private javax.swing.JLabel jLusuario1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTAinfoCedulaOriginal;
    private javax.swing.JTextField jTapellidos;
    private javax.swing.JTextField jTdigitoVerifi;
    private javax.swing.JTextField jTdireccion;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTid;
    private javax.swing.JTextField jTnombres;
    private javax.swing.JTextField jTnroIdentif;
    private javax.swing.JTextField jTnroIdentifCliente;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField jTotrosNombre;
    private javax.swing.JTextField jTrazonSocial;
    private javax.swing.JTextField jTsegundoApellido;
    private javax.swing.JTextField jTtelefono;
    private javax.swing.JButton jbtnCargaDocumento;
    private javax.swing.JButton jbtnCargaDocumento3;
    private javax.swing.JTextField jtficha1;
    private javax.swing.JTextField jtficha2;
    // End of variables declaration//GEN-END:variables
///VERIFICA SI EXISTE O NO EL CLIENTE
    private void buscanit() {

        try {
            //llamamos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            String nroIdentificacion = jTnroIdentif.getText();

            ResultSet resultado = estado.executeQuery("SELECT * FROM infoclientes  WHERE  dniNit = '" + nroIdentificacion + "'  ");

            //inicialisamos las variables de tipo String
            String primernombre = null, razonSocial = null, otrosNombre = null, apellidos = null, segundoApellido = null,
                    nroIdentibene = null, digitoVerificacion = null, direccion = null, email = null, naturaleza = null,
                    telefonoCodigo = null, Identicliente = null, carta = null, cedula = null, infcedulaoriginal = null, nroIdenti = null, descripcioActividadEconomica = null;

            //inicialisamos las variables de tipo Object
            Object tipoDocumento = null, actividadEconomica = null, codigoPais = null, codigoDepartamento = null,
                    codigoMunicipio = null;

            //String fechaNacimiento, fechaIngreso, fechaInicialContrato, fechaFinalContrato, fechaCamaraComercio, fechaExpedicion;
            while (resultado.next()) {

                primernombre = resultado.getString("bene1nombre");
                otrosNombre = resultado.getString("bene2nombre");
                apellidos = resultado.getString("bene1apellido");
                segundoApellido = resultado.getString("bene2apellido");
                tipoDocumento = resultado.getObject("benetipodni");
                nroIdenti = resultado.getString("dniNit");
                digitoVerificacion = resultado.getString("digverifica");
                nroIdentibene = resultado.getString("benedni");
                carta = resultado.getString("benecartaautoriza");
                cedula = resultado.getString("benecedula");
                infcedulaoriginal = resultado.getString("beneinfcedula");
                direccion = resultado.getString("direccion");
                actividadEconomica = resultado.getObject("actEconomica");
                codigoPais = resultado.getObject("pais");
                codigoDepartamento = resultado.getObject("departamento");
                codigoMunicipio = resultado.getObject("municipio");
                email = resultado.getString("email");
                naturaleza = (String) resultado.getObject("naturaleza");
                razonSocial = resultado.getString("razonSocial");
                telefonoCodigo = resultado.getString("telefono");
                descripcioActividadEconomica = resultado.getString("infoactividadeconomica");
                jTid.setText(Integer.toString(resultado.getInt("id"))); //envia el nomero del id a la caja

            }

            // le recuerda al usuario que debe de llenar los campos para hacer la validacion
            if (nroIdentificacion.equals(nroIdenti)) {

                JOptionPane.showMessageDialog(null, "PROVEEDOR ENCONTRADO");
                

            
                
                  //desabilito campos para forzar a que el usuario verifique si existe el proveedor buscanit();
        jCnaturaleza.setEnabled(false);
        jTrazonSocial.setEnabled(false);
        jTnroIdentif.setEnabled(false);
        jTid.setEnabled(false);
        jTdireccion.setEnabled(false);
        jTtelefono.setEnabled(false);
       jCcodigoMunic.setEnabled(false);
        jCactividadEco.setEnabled(false);
        jCcodigoPais.setEnabled(false);
        jCcodigoDepart.setEnabled(false);
        jTemail.setEnabled(false);
        jTnombres.setEnabled(false);
        jTotrosNombre.setEnabled(false);
        jTapellidos.setEnabled(false);
        jTsegundoApellido.setEnabled(false);
        jCtipoDocumento.setEnabled(false);
        jTnroIdentifCliente.setEnabled(false);
        jtficha1.setEnabled(false);
        jtficha2.setEnabled(false);
        jTAinfoCedulaOriginal.setEnabled(false);
        jBguardar.setEnabled(false);
        jBbuscar.setEnabled(false);
        
        
        
        jToggleButton3.requestFocus();

//                     jBregistrar.setEnabled(false);
//                     jBmodificar.setEnabled(true);
//                     jBeliminar.setEnabled(true);
                //carga los datos que tienen las variables en los jtextfiel
                jTnombres.setText(primernombre);
                jTotrosNombre.setText(otrosNombre);
                jTapellidos.setText(apellidos);
                jTsegundoApellido.setText(segundoApellido);
                jCtipoDocumento.setSelectedItem(tipoDocumento);
                jTnroIdentif.setText(nroIdenti);
                jTdigitoVerifi.setText(digitoVerificacion);
                jTdireccion.setText(direccion);
                jCactividadEco.setSelectedItem(actividadEconomica);
                jCcodigoPais.setSelectedItem(codigoPais);
                jCcodigoDepart.setSelectedItem(codigoDepartamento);
                jCcodigoMunic.setSelectedItem(codigoMunicipio);
                jTemail.setText(email);
                jCnaturaleza.setSelectedItem(naturaleza);
                jTrazonSocial.setText(razonSocial);
                jTtelefono.setText(telefonoCodigo);
                jTnroIdentifCliente.setText(nroIdentibene);
                jtficha1.setText(carta);
                jtficha2.setText(cedula);
                jTAinfoCedulaOriginal.setText(infcedulaoriginal);
                jLdescripcion.setText(descripcioActividadEconomica);

            } else {
                JOptionPane.showMessageDialog(null, "Nit no encontrado");

                limpiar();

            }

        } catch (SQLException ex) {
            System.out.println(ex);

        }

    }
     private void limpiar() {
        //limpia los campos
      
        jCnaturaleza.setSelectedItem(null);
        jTrazonSocial.setText(" ");
        jTnroIdentif.setText(" ");
        jTdigitoVerifi.setText(" ");
        jTdireccion.setText(" ");
        jTtelefono.setText(" ");
        jCcodigoMunic.setSelectedItem(null);
        jCactividadEco.setSelectedItem(null);
        jCcodigoPais.setSelectedItem(null);
        jCcodigoDepart.setSelectedItem(null);
        jTnombres.setText(" ");
        jTotrosNombre.setText(" ");
        jTapellidos.setText(" ");
        jTsegundoApellido.setText(" ");
        jCtipoDocumento.setSelectedItem(null);
        jTnroIdentifCliente.setText(" ");
        jtficha1.setText(" ");
        jtficha2.setText(" ");
        jTAinfoCedulaOriginal.setText(" ");

    }
      ///VERIFICA SI EXISTE O NO EL CLIENTE
    private void verificacionEmpleado() {

        try {
            //llamamos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            String nroIdentificacion = jTnroIdentif.getText();

            ResultSet resultado = estado.executeQuery("SELECT * FROM infoclientes  WHERE  dniNit = '" + nroIdentificacion + "'  ");

            //inicialisamos las variables de tipo String
            String primernombre = null, razonSocial = null, otrosNombre = null, apellidos = null, segundoApellido = null,
                    nroIdentibene = null, digitoVerificacion = null, direccion = null, email = null, naturaleza = null,
                    telefonoCodigo = null, Identicliente = null, carta = null, cedula = null, infcedulaoriginal = null, nroIdenti = null, descripcioActividadEconomica = null;

            //inicialisamos las variables de tipo Object
            Object tipoDocumento = null, actividadEconomica = null, codigoPais = null, codigoDepartamento = null,
                    codigoMunicipio = null;

            //String fechaNacimiento, fechaIngreso, fechaInicialContrato, fechaFinalContrato, fechaCamaraComercio, fechaExpedicion;
            while (resultado.next()) {

                primernombre = resultado.getString("bene1nombre");
                otrosNombre = resultado.getString("bene2nombre");
                apellidos = resultado.getString("bene1apellido");
                segundoApellido = resultado.getString("bene2apellido");
                tipoDocumento = resultado.getObject("benetipodni");
                nroIdenti = resultado.getString("dniNit");
                digitoVerificacion = resultado.getString("digverifica");
                nroIdentibene = resultado.getString("benedni");
                carta = resultado.getString("benecartaautoriza");
                cedula = resultado.getString("benecedula");
                infcedulaoriginal = resultado.getString("beneinfcedula");
                direccion = resultado.getString("direccion");
                actividadEconomica = resultado.getObject("actEconomica");
                codigoPais = resultado.getObject("pais");
                codigoDepartamento = resultado.getObject("departamento");
                codigoMunicipio = resultado.getObject("municipio");
                email = resultado.getString("email");
                naturaleza = (String) resultado.getObject("naturaleza");
                razonSocial = resultado.getString("razonSocial");
                telefonoCodigo = resultado.getString("telefono");
                descripcioActividadEconomica = resultado.getString("descripcioActividadEconomica");
                jTid.setText(Integer.toString(resultado.getInt("id"))); //envia el nomero del id a la caja

            }

            // le recuerda al usuario que debe de llenar los campos para hacer la validacion
            if (nroIdentificacion.equals(nroIdenti)) {

                JOptionPane.showMessageDialog(null, "El registro ya existe");

//                     jBregistrar.setEnabled(false);
//                     jBmodificar.setEnabled(true);
//                     jBeliminar.setEnabled(true);
                //carga los datos que tienen las variables en los jtextfiel
                jTnombres.setText(primernombre);
                jTotrosNombre.setText(otrosNombre);
                jTapellidos.setText(apellidos);
                jTsegundoApellido.setText(segundoApellido);
                jCtipoDocumento.setSelectedItem(tipoDocumento);
                jTnroIdentif.setText(nroIdenti);
                jTdigitoVerifi.setText(digitoVerificacion);
                jTdireccion.setText(direccion);
                jCactividadEco.setSelectedItem(actividadEconomica);
                jCcodigoPais.setSelectedItem(codigoPais);
                jCcodigoDepart.setSelectedItem(codigoDepartamento);
                jCcodigoMunic.setSelectedItem(codigoMunicipio);
                jTemail.setText(email);
                jCnaturaleza.setSelectedItem(naturaleza);
                jTrazonSocial.setText(razonSocial);
                jTtelefono.setText(telefonoCodigo);
                jTnroIdentifCliente.setText(nroIdentibene);
                jtficha1.setText(carta);
                jtficha2.setText(cedula);
                jTAinfoCedulaOriginal.setText(infcedulaoriginal);
                jLdescripcion.setText(descripcioActividadEconomica);

            } else {
                //nos manda a la sentencia que se encarga de capturar y mandar la informacion a la base de datos
                nuevoRegistro();

            }

        } catch (SQLException ex) {
            System.out.println(ex);

        }

    }
    private void selectcodmunicipio() {

        try {

            // hacemos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            // Se realiza la consulta
            String departamentoescogido = (String) jCcodigoDepart.getSelectedItem();
            // JOptionPane.showMessageDialog(null, departamentoescogido);
            ResultSet resultado = estado.executeQuery("SELECT * FROM codmunicipios where departamento = '" + departamentoescogido + "'");

            // Bucle while para la consulta
            jCcodigoMunic.addItem(" ");
            while (resultado.next()) {
                // Comenzamos a rellenar el combobox a partir de la consulta

                jCcodigoMunic.addItem(resultado.getObject("municipio"));

            }
            cn.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }
     private void nuevoRegistro() {

        if (jTtelefono.getText().equals("") || jTnroIdentif.getText().equals("") || jTnombres.getText().equals("") || jTapellidos.getText().equals("") || jTnroIdentifCliente.getText().equals("")
                || jtficha1.getText().equals("") || jtficha2.getText().equals("") || jTAinfoCedulaOriginal.getText().equals("")
                || jTdireccion.getText().equals("") || jCactividadEco.getSelectedItem().equals("") || jCcodigoPais.getSelectedItem().equals("") || jCcodigoDepart.getSelectedItem().equals("")
                || jCcodigoMunic.getSelectedItem().equals("")) {

            JOptionPane.showMessageDialog(null, "Debe diligenciar los campos obligatorios *", "Atencion", JOptionPane.WARNING_MESSAGE);

        } else {

            conexion conectarsql = new conexion();

            Connection cn = conectarsql.conectar();
        //conectarsql.conectar();

            //inicialisamos las variables de tipo String
            String primernombre = null, razonSocial = null, otrosNombre = null, apellidos = null, segundoApellido = null,
                    nroIdentibene = null, digitoVerificacion = null, direccion = null, email = null,
                    telefonoCodigo = null, Identicliente = null, descripcioActividadEconomica = null, carta = null, cedula = null, infcedulaoriginal = null, nroIdenti = null;

            //inicialisamos las variables de tipo Object
            Object tipoDocumento = null, actividadEconomica = null, codigoPais = null, codigoDepartamento = null,
                    codigoMunicipio = null, naturaleza = null;

            String sql;
            // obtenemos la informacion que trae cada una de las cajas LUIS FDO 11julio 2013

            primernombre = jTnombres.getText();
            razonSocial = jTrazonSocial.getText();
            otrosNombre = jTotrosNombre.getText();
            apellidos = jTapellidos.getText();
            segundoApellido = jTsegundoApellido.getText();
            tipoDocumento = jCtipoDocumento.getSelectedItem();
            nroIdenti = jTnroIdentif.getText();
            digitoVerificacion = jTdigitoVerifi.getText();
            direccion = jTdireccion.getText();
            email = jTemail.getText();
            naturaleza = jCnaturaleza.getSelectedItem();
            telefonoCodigo = jTtelefono.getText();
            nroIdentibene = jTnroIdentifCliente.getText();
            carta = jtficha1.getText();
            cedula = jtficha2.getText();
            infcedulaoriginal = jTAinfoCedulaOriginal.getText();
            actividadEconomica = jCactividadEco.getSelectedItem();
            codigoPais = jCcodigoPais.getSelectedItem();
            codigoDepartamento = jCcodigoDepart.getSelectedItem();
            codigoMunicipio = jCcodigoMunic.getSelectedItem();
            descripcioActividadEconomica = jLdescripcion.getText();

            // seleccionamos la tabla a la cual van los datos
            sql = "INSERT INTO infoclientes (naturaleza, razonSocial, dniNit, digverifica, direccion, telefono, municipio, actEconomica, pais, email, departamento, bene1nombre, bene2nombre, bene1apellido, bene2apellido, benetipodni, benedni, benecartaautoriza, benecedula, beneinfcedula, infoactividadeconomica) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            try {

                java.sql.PreparedStatement pst = cn.prepareStatement(sql);

                //estas pst.setString envia el valor que hay en la variable al campo 1 que es igual a la primera ? en values y asi
                pst.setObject(1, naturaleza);
                pst.setString(2, razonSocial);
                pst.setString(3, nroIdenti);
                pst.setString(4, digitoVerificacion);
                pst.setObject(5, direccion);
                pst.setObject(6, telefonoCodigo);
                pst.setObject(7, codigoMunicipio);
                pst.setObject(8, actividadEconomica);
                pst.setObject(9, codigoPais);
                pst.setString(10, email);
                pst.setObject(11, codigoDepartamento);
                pst.setString(12, primernombre);
                pst.setString(13, otrosNombre);
                pst.setString(14, apellidos);
                pst.setString(15, segundoApellido);
                pst.setObject(16, tipoDocumento);
                pst.setString(17, nroIdentibene);
                pst.setString(18, carta);
                pst.setString(19, cedula);
                pst.setString(20, infcedulaoriginal);
                pst.setString(21, descripcioActividadEconomica);

                int n = pst.executeUpdate();
                if (n > 0) {

                    cn.close();
                    JOptionPane.showMessageDialog(null, "exito al guardar", "Atencion", JOptionPane.INFORMATION_MESSAGE);

                    limpiar();
                    initComponents();
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);
                System.out.println(ex);
                initComponents();
            }

        }

    }
     
    //metodo que se encarga de ir a la base de datos y traer los diferentes tipos de documentos para que el usuario pueda seleccionar
    private void seleccioneTipoDocumento() {

        try {

            // hacemos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            // Se realiza la consulta
            ResultSet resultado = estado.executeQuery("SELECT codigo, descripcion FROM tipodocumento");

            // Bucle while para la consulta
            jCtipoDocumento.addItem(" ");
            while (resultado.next()) {
                // Comenzamos a rellenar el combobox a partir de la consulta

                jCtipoDocumento.addItem(resultado.getObject("descripcion"));

            }
            cn.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    //nos carga los paises en elcombobox
    private void seleccionePais() {

        try {

            // hacemos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            // Se realiza la consulta
            ResultSet resultado = estado.executeQuery("SELECT * FROM codigospaises");

            // Bucle while para la consulta
            jCcodigoPais.addItem(" ");
            while (resultado.next()) {
                // Comenzamos a rellenar el combobox a partir de la consulta

                jCcodigoPais.addItem(resultado.getObject("nombrepais"));

            }
            cn.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    //metodo que se encarga de ir a traer los departamentos para que el usuario pueda descojer
    private void seleccioneDepartamento() {

        try {

            // hacemos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            // Se realiza la consulta
            ResultSet resultado = estado.executeQuery("SELECT * FROM coddepartamento");

            // Bucle while para la consulta
            jCcodigoDepart.addItem(" ");
            while (resultado.next()) {
                // Comenzamos a rellenar el combobox a partir de la consulta

                jCcodigoDepart.addItem(resultado.getObject("departamento"));

            }
            cn.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }

    private void codigoActividadEconomica() {

        try {

            // hacemos la conexion
            conexion cc = new conexion();
            Connection cn = cc.conectar();
            Statement estado = cn.createStatement();

            // Se realiza la consulta
            String descripcion = "";
            ResultSet resultado = estado.executeQuery("SELECT * FROM acteconomicas ");

            // Bucle while para la consulta
            jCactividadEco.addItem(" ");
            while (resultado.next()) {
                // Comenzamos a rellenar el combobox a partir de la consulta

                jCactividadEco.addItem(resultado.getObject("codigo"));

                descripcion = resultado.getString("descripcion");
            }

            //jLdescripcion.setText(descripcion);
            cn.close();

        } catch (Exception e) {
            System.out.println(e);

        }

    }
      void pasar(String user, String tipousuario) {

        jLusuario.setText(user);
        jLrol.setText(tipousuario);

        Calendar cal = Calendar.getInstance();

//sentencia que nos carga la fecha actual en la interfaz
        int diaHoy = cal.get(Calendar.DAY_OF_MONTH);
        int mes = cal.get(Calendar.MONTH) + 1;
        int año = cal.get(Calendar.YEAR);
        int hora = cal.get(Calendar.HOUR);
        int minutos = cal.get(Calendar.MINUTE);
        int AMPM = cal.get(Calendar.AM_PM);

        try {
            if (hora < 12) {
                String PM = "";
                if (AMPM == 1) {
                    PM = "PM";
                }
                jLfecha.setText(diaHoy + "/" + mes + "/" + año);

            } else if (hora > 12) {
                String AM = "";
                if (AMPM == 0) {
                    AM = "AM";
                }
                jLfecha.setText(diaHoy + "/" + mes + "/" + año);

            }
        } catch (Exception e) {
        }

    }

}
